project:
  type: website

website:
  title: "ELLA KAYE"
  site-url: "https://ellakaye.rbind.io"
  repo-url: https://github.com/EllaKaye/ellakaye-quarto
  repo-actions: issue
#  image:
#  image-alt:
  navbar:
    #logo: ELLAKAYE-logo-light.png
    title: "ELLA<span class='icon-line'></span>KAYE"
    right:
      - text: about
        href: about.qmd
      - posts.qmd
      - talks.qmd
      - projects.qmd
      - text: contact
        href: contact.qmd
      #- icon: github
      #  href: https://github.com/EllaKaye
      #- icon: twitter
      #  href: https://twitter.com/ellamkaye
  favicon: images/favicon.png
  twitter-card: 
    description: The personal website of Ella Kaye
    image: "images/logo-white-background.png"
    image-alt: |
      A logo made from Ella Kaye's name - 
      first name on top of last name in dark gray capital letters, 
      separated by a horizontal bright pink line, on a white background"
    image-width: 500
    image-height: 500
    card-style: summary # alternative summary_large_image
    creator: "@ellamkaye"
    site: "@ellamkaye"
  open-graph: 
    #description: The personal website of Ella Kaye
    image: "images/logo-white-background.png"
    image-alt: |
      A logo made from Ella Kaye's name - 
      first name on top of last name in dark gray capital letters, 
      separated by a horizontal bright pink line, on a white background"
    image-width: 500
    image-height: 500
    locale: en-GB
  google-analytics: "UA-101621242-1"
    

format:
  html:
    #metadata: 
    #  pagetitle: "Ella Kaye"
    theme: 
      light: ek-theme-light.scss
      dark: ek-theme-dark.scss
    css: ek-styles.css
    code-block-border-left: true
    highlight-style: 
      light: ek-light.theme
      dark: ek-dark.theme
    smooth-scroll: true
    
editor: source

