project:
  type: website

website:
  title: "ELLA KAYE"
  favicon: images/favicon.png
  navbar:
    logo: ELLAKAYE-logo-light.png
    title: false
    right:
      - posts.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: 
      light: ek-theme.scss
      #dark: ek-theme-dark.scss
    code-block-border-left: true
    highlight-style: ek-syntax-highlighting.theme

editor: source

